### ISSUE TITLE
AttributeError: 'RandomMirroredDataset' object has no attribute 'word_count'

### ISSUE THREAD

**Issue by qoopen0815** [google-research/perceiver-ar#6]
Dear all.

I would like to try perceiver-ar on my own PC, but I can't solve the following error.
I checked your code, but as per the error, I can't find the function word_count(). So could you please help me with a solution?

### command
I'm trying to evaluate a latest learning model with the following command.

```bash
(perceiver-ar) qoopen@Z390:~/perceiver-ar$ PYTHONPATH=.::$PYTHONPATH python experiment.py  --config=experiment.py:random_mirrored_32   --jaxline_mode=eval   --config.one_off_evaluate=True   --config.restore_path="${LATEST_CHECKPOINT}"
```

### error message

```bash
Traceback (most recent call last):
  File "experiment.py", line 1231, in <module>
    app.run(lambda argv: main(argv, Experiment))
  File "/home/qoopen/.venv/perceiver-ar/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/qoopen/.venv/perceiver-ar/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "experiment.py", line 1231, in <lambda>
    app.run(lambda argv: main(argv, Experiment))
  File "experiment.py", line 1224, in main
    platform.main(experiment_class, argv)
  File "/home/qoopen/.venv/perceiver-ar/lib/python3.8/site-packages/jaxline/utils.py", line 484, in inner_wrapper
    return f(*args, **kwargs)
  File "/home/qoopen/.venv/perceiver-ar/lib/python3.8/site-packages/jaxline/platform.py", line 137, in main
    train.evaluate(experiment_class, config, checkpointer, writer,
  File "/home/qoopen/.venv/perceiver-ar/lib/python3.8/site-packages/jaxline/utils.py", line 620, in inner_wrapper
    return fn(*args, **kwargs)
  File "/home/qoopen/.venv/perceiver-ar/lib/python3.8/site-packages/jaxline/train.py", line 196, in evaluate
    scalar_values = utils.evaluate_should_return_dict(experiment.evaluate)(
  File "/home/qoopen/.venv/perceiver-ar/lib/python3.8/site-packages/jaxline/utils.py", line 521, in evaluate_with_warning
    evaluate_out = f(*args, **kwargs)
  File "experiment.py", line 924, in evaluate
    scalars = jax.device_get(self._eval_epoch(rng, global_step))
  File "experiment.py", line 1102, in _eval_epoch
    ds_iter = self._build_eval_input()
  File "experiment.py", line 1049, in _build_eval_input
    return self._eval_input, self._dataset.word_count(split)
AttributeError: 'RandomMirroredDataset' object has no attribute 'word_count'
```

**Comment by cghawthorne** [comment]
Thanks! Should be fixed now.

Note that evaluation is currently over ~1M examples, so you may want to decrease that number for faster testing: https://github.com/google-research/perceiver-ar/blob/891594bbeedd1a11430b4fb4dafede8c25b741c3/perceiver_ar/dataset.py#L242

**Comment by qoopen0815** [comment]
Thanks for your correction !!
